@host = http://localhost:3000
# @host = https://mbti-detective-api.netlify.app
# @host = https://mbti-detective-api.fly.dev

POST {{host}}/api/participants HTTP/1.1
content-type: application/json

{
    "name": "아무개5",
    "user_key": "f3BVUBUIen",
    "mbti": "estp"
}

###

POST {{host}}/api/share/plus HTTP/1.1
content-type: application/json

###

POST {{host}}/api/users HTTP/1.1
content-type: application/json

{
    "name": "아무개3",
    "mbti": "estp"
}